### ISSUE TITLE
Is this still working..?

### ISSUE THREAD

**Issue by malthew** [That-Half-Dead-Skeleton/text-analyzer#1]
Using this package with the examples given in the docs, I get the following error, which makes me question whether this package even works or not?

Error:
`PerspectiveAnalyzerError: [TOXICITY ANALYZER ERROR] An error occurred while analyzing the text.`

**Comment by SebastianMostert** [comment]
Hey there sorry for the late reply, I've been busy with school and work.

I'll try and get it fixed by the end of the day, I will email you once it's
done, thank you for your report and for using the package!

**Comment by SebastianMostert** [comment]
Status update, I have gotten a working version up again, I had forgotten to updated the README file.

I'll have everything finished by around 19:00 UTC

**Comment by SebastianMostert** [comment]
I published the new update now, please let me know if any issues persist. Keep in mind you will need to update your code to use the new system, please review the README file for any questions, or open a new issue
